-- 011_rls_enable.sql
-- GENERATED by `pnpm db:gen-rls` (database/scripts/gen-rls.ts). Do not hand-edit.
-- One ENABLE + FORCE per tenant-reachable table. See 08-TEAM-SYSTEMS.md §3.3.

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'org_entitlements',
    'usage_records',
    'identity_providers',
    'domain_claims',
    'invitations',
    'support_access_grants',
    'users',
    'memberships',
    'audit_logs',
    'projects',
    'embeddings',
    'tests',
    'agents',
    'tenant_agent_pins',
    'agent_runs',
    'executions',
    'artifacts',
    'failures',
    'issues',
    'project_members',
    'refresh_tokens',
    'key_counters',
    'folders',
    'tags',
    'test_plans',
    'quality_snapshots',
    'applications',
    'test_steps',
    'test_preconditions',
    'test_validations',
    'test_versions',
    'test_tags',
    'test_data_sets',
    'test_dependencies',
    'agent_tool_grants',
    'agent_actions',
    'ai_proposals',
    'healing_attempts',
    'failure_analyses',
    'execution_tests',
    'execution_events',
    'issue_tests',
    'issue_comments',
    'issue_history',
    'issue_artifacts',
    'environments',
    'app_pages',
    'app_flows',
    'explorations',
    'execution_steps',
    'app_credentials',
    'app_components',
    'app_elements',
    'app_flow_pages',
    'app_transitions'
  ]
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE public.%I FORCE  ROW LEVEL SECURITY', t);
  END LOOP;
END $$;
