-- 012_rls_policies.sql
-- GENERATED by `pnpm db:gen-rls` (database/scripts/gen-rls.ts). Do not hand-edit.
-- See 08-TEAM-SYSTEMS.md §3.3-3.4 for the USING/WITH CHECK rationale and the
-- EXISTS-subquery-over-denormalization decision for child tables.

-- ── Direct: org_id is a column on the table itself ──────────────────────────

CREATE POLICY tenant_isolation ON org_entitlements
  USING      (org_id = current_setting('app.current_org_id', true)::uuid)
  WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid);

CREATE POLICY tenant_isolation ON usage_records
  USING      (org_id = current_setting('app.current_org_id', true)::uuid)
  WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid);

CREATE POLICY tenant_isolation ON identity_providers
  USING      (org_id = current_setting('app.current_org_id', true)::uuid)
  WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid);

CREATE POLICY tenant_isolation ON domain_claims
  USING      (org_id = current_setting('app.current_org_id', true)::uuid)
  WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid);

CREATE POLICY tenant_isolation ON invitations
  USING      (org_id = current_setting('app.current_org_id', true)::uuid)
  WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid);

CREATE POLICY tenant_isolation ON support_access_grants
  USING      (org_id = current_setting('app.current_org_id', true)::uuid)
  WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid);

CREATE POLICY tenant_isolation ON users
  USING      (org_id = current_setting('app.current_org_id', true)::uuid)
  WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid);

CREATE POLICY tenant_isolation ON memberships
  USING      (org_id = current_setting('app.current_org_id', true)::uuid)
  WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid);

CREATE POLICY tenant_isolation ON audit_logs
  USING      (org_id = current_setting('app.current_org_id', true)::uuid)
  WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid);

CREATE POLICY tenant_isolation ON projects
  USING      (org_id = current_setting('app.current_org_id', true)::uuid)
  WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid);

CREATE POLICY tenant_isolation ON embeddings
  USING      (org_id = current_setting('app.current_org_id', true)::uuid)
  WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid);

CREATE POLICY tenant_isolation ON tests
  USING      (org_id = current_setting('app.current_org_id', true)::uuid)
  WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid);

CREATE POLICY tenant_isolation ON agents
  USING      (org_id = current_setting('app.current_org_id', true)::uuid)
  WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid);

CREATE POLICY tenant_isolation ON tenant_agent_pins
  USING      (org_id = current_setting('app.current_org_id', true)::uuid)
  WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid);

CREATE POLICY tenant_isolation ON agent_runs
  USING      (org_id = current_setting('app.current_org_id', true)::uuid)
  WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid);

CREATE POLICY tenant_isolation ON executions
  USING      (org_id = current_setting('app.current_org_id', true)::uuid)
  WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid);

CREATE POLICY tenant_isolation ON artifacts
  USING      (org_id = current_setting('app.current_org_id', true)::uuid)
  WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid);

CREATE POLICY tenant_isolation ON failures
  USING      (org_id = current_setting('app.current_org_id', true)::uuid)
  WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid);

CREATE POLICY tenant_isolation ON issues
  USING      (org_id = current_setting('app.current_org_id', true)::uuid)
  WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid);

-- ── Reached via a parent (one predicate per hop, innermost first) ───────────

CREATE POLICY tenant_isolation ON project_members
  USING      (EXISTS (
    SELECT 1 FROM projects p_projects
     WHERE p_projects.id = project_members.project_id
       AND p_projects.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM projects p_projects
     WHERE p_projects.id = project_members.project_id
       AND p_projects.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON refresh_tokens
  USING      (EXISTS (
    SELECT 1 FROM users p_users
     WHERE p_users.id = refresh_tokens.user_id
       AND p_users.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM users p_users
     WHERE p_users.id = refresh_tokens.user_id
       AND p_users.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON key_counters
  USING      (EXISTS (
    SELECT 1 FROM projects p_projects
     WHERE p_projects.id = key_counters.project_id
       AND p_projects.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM projects p_projects
     WHERE p_projects.id = key_counters.project_id
       AND p_projects.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON folders
  USING      (EXISTS (
    SELECT 1 FROM projects p_projects
     WHERE p_projects.id = folders.project_id
       AND p_projects.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM projects p_projects
     WHERE p_projects.id = folders.project_id
       AND p_projects.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON tags
  USING      (EXISTS (
    SELECT 1 FROM projects p_projects
     WHERE p_projects.id = tags.project_id
       AND p_projects.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM projects p_projects
     WHERE p_projects.id = tags.project_id
       AND p_projects.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON test_plans
  USING      (EXISTS (
    SELECT 1 FROM projects p_projects
     WHERE p_projects.id = test_plans.project_id
       AND p_projects.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM projects p_projects
     WHERE p_projects.id = test_plans.project_id
       AND p_projects.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON quality_snapshots
  USING      (EXISTS (
    SELECT 1 FROM projects p_projects
     WHERE p_projects.id = quality_snapshots.project_id
       AND p_projects.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM projects p_projects
     WHERE p_projects.id = quality_snapshots.project_id
       AND p_projects.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON applications
  USING      (EXISTS (
    SELECT 1 FROM projects p_projects
     WHERE p_projects.id = applications.project_id
       AND p_projects.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM projects p_projects
     WHERE p_projects.id = applications.project_id
       AND p_projects.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON test_steps
  USING      (EXISTS (
    SELECT 1 FROM tests p_tests
     WHERE p_tests.id = test_steps.test_id
       AND p_tests.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM tests p_tests
     WHERE p_tests.id = test_steps.test_id
       AND p_tests.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON test_preconditions
  USING      (EXISTS (
    SELECT 1 FROM tests p_tests
     WHERE p_tests.id = test_preconditions.test_id
       AND p_tests.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM tests p_tests
     WHERE p_tests.id = test_preconditions.test_id
       AND p_tests.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON test_validations
  USING      (EXISTS (
    SELECT 1 FROM tests p_tests
     WHERE p_tests.id = test_validations.test_id
       AND p_tests.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM tests p_tests
     WHERE p_tests.id = test_validations.test_id
       AND p_tests.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON test_versions
  USING      (EXISTS (
    SELECT 1 FROM tests p_tests
     WHERE p_tests.id = test_versions.test_id
       AND p_tests.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM tests p_tests
     WHERE p_tests.id = test_versions.test_id
       AND p_tests.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON test_tags
  USING      (EXISTS (
    SELECT 1 FROM tests p_tests
     WHERE p_tests.id = test_tags.test_id
       AND p_tests.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM tests p_tests
     WHERE p_tests.id = test_tags.test_id
       AND p_tests.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON test_data_sets
  USING      (EXISTS (
    SELECT 1 FROM tests p_tests
     WHERE p_tests.id = test_data_sets.test_id
       AND p_tests.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM tests p_tests
     WHERE p_tests.id = test_data_sets.test_id
       AND p_tests.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON test_dependencies
  USING      (EXISTS (
    SELECT 1 FROM tests p_tests
     WHERE p_tests.id = test_dependencies.test_id
       AND p_tests.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM tests p_tests
     WHERE p_tests.id = test_dependencies.test_id
       AND p_tests.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON agent_tool_grants
  USING      (EXISTS (
    SELECT 1 FROM agents p_agents
     WHERE p_agents.id = agent_tool_grants.agent_id
       AND p_agents.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM agents p_agents
     WHERE p_agents.id = agent_tool_grants.agent_id
       AND p_agents.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON agent_actions
  USING      (EXISTS (
    SELECT 1 FROM agent_runs p_agent_runs
     WHERE p_agent_runs.id = agent_actions.agent_run_id
       AND p_agent_runs.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM agent_runs p_agent_runs
     WHERE p_agent_runs.id = agent_actions.agent_run_id
       AND p_agent_runs.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON ai_proposals
  USING      (EXISTS (
    SELECT 1 FROM agent_runs p_agent_runs
     WHERE p_agent_runs.id = ai_proposals.agent_run_id
       AND p_agent_runs.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM agent_runs p_agent_runs
     WHERE p_agent_runs.id = ai_proposals.agent_run_id
       AND p_agent_runs.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON healing_attempts
  USING      (EXISTS (
    SELECT 1 FROM agent_runs p_agent_runs
     WHERE p_agent_runs.id = healing_attempts.agent_run_id
       AND p_agent_runs.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM agent_runs p_agent_runs
     WHERE p_agent_runs.id = healing_attempts.agent_run_id
       AND p_agent_runs.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON failure_analyses
  USING      (EXISTS (
    SELECT 1 FROM agent_runs p_agent_runs
     WHERE p_agent_runs.id = failure_analyses.agent_run_id
       AND p_agent_runs.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM agent_runs p_agent_runs
     WHERE p_agent_runs.id = failure_analyses.agent_run_id
       AND p_agent_runs.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON execution_tests
  USING      (EXISTS (
    SELECT 1 FROM executions p_executions
     WHERE p_executions.id = execution_tests.execution_id
       AND p_executions.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM executions p_executions
     WHERE p_executions.id = execution_tests.execution_id
       AND p_executions.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON execution_events
  USING      (EXISTS (
    SELECT 1 FROM executions p_executions
     WHERE p_executions.id = execution_events.execution_id
       AND p_executions.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM executions p_executions
     WHERE p_executions.id = execution_events.execution_id
       AND p_executions.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON issue_tests
  USING      (EXISTS (
    SELECT 1 FROM issues p_issues
     WHERE p_issues.id = issue_tests.issue_id
       AND p_issues.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM issues p_issues
     WHERE p_issues.id = issue_tests.issue_id
       AND p_issues.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON issue_comments
  USING      (EXISTS (
    SELECT 1 FROM issues p_issues
     WHERE p_issues.id = issue_comments.issue_id
       AND p_issues.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM issues p_issues
     WHERE p_issues.id = issue_comments.issue_id
       AND p_issues.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON issue_history
  USING      (EXISTS (
    SELECT 1 FROM issues p_issues
     WHERE p_issues.id = issue_history.issue_id
       AND p_issues.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM issues p_issues
     WHERE p_issues.id = issue_history.issue_id
       AND p_issues.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON issue_artifacts
  USING      (EXISTS (
    SELECT 1 FROM issues p_issues
     WHERE p_issues.id = issue_artifacts.issue_id
       AND p_issues.org_id = current_setting('app.current_org_id', true)::uuid))
  WITH CHECK (EXISTS (
    SELECT 1 FROM issues p_issues
     WHERE p_issues.id = issue_artifacts.issue_id
       AND p_issues.org_id = current_setting('app.current_org_id', true)::uuid));

CREATE POLICY tenant_isolation ON environments
  USING      (EXISTS (
    SELECT 1 FROM applications p_applications
     WHERE p_applications.id = environments.application_id
       AND EXISTS (
       SELECT 1 FROM projects p2_projects
        WHERE p2_projects.id = p_applications.project_id
          AND p2_projects.org_id = current_setting('app.current_org_id', true)::uuid)))
  WITH CHECK (EXISTS (
    SELECT 1 FROM applications p_applications
     WHERE p_applications.id = environments.application_id
       AND EXISTS (
       SELECT 1 FROM projects p2_projects
        WHERE p2_projects.id = p_applications.project_id
          AND p2_projects.org_id = current_setting('app.current_org_id', true)::uuid)));

CREATE POLICY tenant_isolation ON app_pages
  USING      (EXISTS (
    SELECT 1 FROM applications p_applications
     WHERE p_applications.id = app_pages.application_id
       AND EXISTS (
       SELECT 1 FROM projects p2_projects
        WHERE p2_projects.id = p_applications.project_id
          AND p2_projects.org_id = current_setting('app.current_org_id', true)::uuid)))
  WITH CHECK (EXISTS (
    SELECT 1 FROM applications p_applications
     WHERE p_applications.id = app_pages.application_id
       AND EXISTS (
       SELECT 1 FROM projects p2_projects
        WHERE p2_projects.id = p_applications.project_id
          AND p2_projects.org_id = current_setting('app.current_org_id', true)::uuid)));

CREATE POLICY tenant_isolation ON app_flows
  USING      (EXISTS (
    SELECT 1 FROM applications p_applications
     WHERE p_applications.id = app_flows.application_id
       AND EXISTS (
       SELECT 1 FROM projects p2_projects
        WHERE p2_projects.id = p_applications.project_id
          AND p2_projects.org_id = current_setting('app.current_org_id', true)::uuid)))
  WITH CHECK (EXISTS (
    SELECT 1 FROM applications p_applications
     WHERE p_applications.id = app_flows.application_id
       AND EXISTS (
       SELECT 1 FROM projects p2_projects
        WHERE p2_projects.id = p_applications.project_id
          AND p2_projects.org_id = current_setting('app.current_org_id', true)::uuid)));

CREATE POLICY tenant_isolation ON explorations
  USING      (EXISTS (
    SELECT 1 FROM applications p_applications
     WHERE p_applications.id = explorations.application_id
       AND EXISTS (
       SELECT 1 FROM projects p2_projects
        WHERE p2_projects.id = p_applications.project_id
          AND p2_projects.org_id = current_setting('app.current_org_id', true)::uuid)))
  WITH CHECK (EXISTS (
    SELECT 1 FROM applications p_applications
     WHERE p_applications.id = explorations.application_id
       AND EXISTS (
       SELECT 1 FROM projects p2_projects
        WHERE p2_projects.id = p_applications.project_id
          AND p2_projects.org_id = current_setting('app.current_org_id', true)::uuid)));

CREATE POLICY tenant_isolation ON execution_steps
  USING      (EXISTS (
    SELECT 1 FROM execution_tests p_execution_tests
     WHERE p_execution_tests.id = execution_steps.execution_test_id
       AND EXISTS (
       SELECT 1 FROM executions p2_executions
        WHERE p2_executions.id = p_execution_tests.execution_id
          AND p2_executions.org_id = current_setting('app.current_org_id', true)::uuid)))
  WITH CHECK (EXISTS (
    SELECT 1 FROM execution_tests p_execution_tests
     WHERE p_execution_tests.id = execution_steps.execution_test_id
       AND EXISTS (
       SELECT 1 FROM executions p2_executions
        WHERE p2_executions.id = p_execution_tests.execution_id
          AND p2_executions.org_id = current_setting('app.current_org_id', true)::uuid)));

CREATE POLICY tenant_isolation ON app_credentials
  USING      (EXISTS (
    SELECT 1 FROM environments p_environments
     WHERE p_environments.id = app_credentials.environment_id
       AND EXISTS (
       SELECT 1 FROM applications p2_applications
        WHERE p2_applications.id = p_environments.application_id
          AND EXISTS (
       SELECT 1 FROM projects p2_projects
        WHERE p2_projects.id = p2_applications.project_id
          AND p2_projects.org_id = current_setting('app.current_org_id', true)::uuid))))
  WITH CHECK (EXISTS (
    SELECT 1 FROM environments p_environments
     WHERE p_environments.id = app_credentials.environment_id
       AND EXISTS (
       SELECT 1 FROM applications p2_applications
        WHERE p2_applications.id = p_environments.application_id
          AND EXISTS (
       SELECT 1 FROM projects p2_projects
        WHERE p2_projects.id = p2_applications.project_id
          AND p2_projects.org_id = current_setting('app.current_org_id', true)::uuid))));

CREATE POLICY tenant_isolation ON app_components
  USING      (EXISTS (
    SELECT 1 FROM app_pages p_app_pages
     WHERE p_app_pages.id = app_components.page_id
       AND EXISTS (
       SELECT 1 FROM applications p2_applications
        WHERE p2_applications.id = p_app_pages.application_id
          AND EXISTS (
       SELECT 1 FROM projects p2_projects
        WHERE p2_projects.id = p2_applications.project_id
          AND p2_projects.org_id = current_setting('app.current_org_id', true)::uuid))))
  WITH CHECK (EXISTS (
    SELECT 1 FROM app_pages p_app_pages
     WHERE p_app_pages.id = app_components.page_id
       AND EXISTS (
       SELECT 1 FROM applications p2_applications
        WHERE p2_applications.id = p_app_pages.application_id
          AND EXISTS (
       SELECT 1 FROM projects p2_projects
        WHERE p2_projects.id = p2_applications.project_id
          AND p2_projects.org_id = current_setting('app.current_org_id', true)::uuid))));

CREATE POLICY tenant_isolation ON app_elements
  USING      (EXISTS (
    SELECT 1 FROM app_pages p_app_pages
     WHERE p_app_pages.id = app_elements.page_id
       AND EXISTS (
       SELECT 1 FROM applications p2_applications
        WHERE p2_applications.id = p_app_pages.application_id
          AND EXISTS (
       SELECT 1 FROM projects p2_projects
        WHERE p2_projects.id = p2_applications.project_id
          AND p2_projects.org_id = current_setting('app.current_org_id', true)::uuid))))
  WITH CHECK (EXISTS (
    SELECT 1 FROM app_pages p_app_pages
     WHERE p_app_pages.id = app_elements.page_id
       AND EXISTS (
       SELECT 1 FROM applications p2_applications
        WHERE p2_applications.id = p_app_pages.application_id
          AND EXISTS (
       SELECT 1 FROM projects p2_projects
        WHERE p2_projects.id = p2_applications.project_id
          AND p2_projects.org_id = current_setting('app.current_org_id', true)::uuid))));

CREATE POLICY tenant_isolation ON app_flow_pages
  USING      (EXISTS (
    SELECT 1 FROM app_flows p_app_flows
     WHERE p_app_flows.id = app_flow_pages.flow_id
       AND EXISTS (
       SELECT 1 FROM applications p2_applications
        WHERE p2_applications.id = p_app_flows.application_id
          AND EXISTS (
       SELECT 1 FROM projects p2_projects
        WHERE p2_projects.id = p2_applications.project_id
          AND p2_projects.org_id = current_setting('app.current_org_id', true)::uuid))))
  WITH CHECK (EXISTS (
    SELECT 1 FROM app_flows p_app_flows
     WHERE p_app_flows.id = app_flow_pages.flow_id
       AND EXISTS (
       SELECT 1 FROM applications p2_applications
        WHERE p2_applications.id = p_app_flows.application_id
          AND EXISTS (
       SELECT 1 FROM projects p2_projects
        WHERE p2_projects.id = p2_applications.project_id
          AND p2_projects.org_id = current_setting('app.current_org_id', true)::uuid))));

CREATE POLICY tenant_isolation ON app_transitions
  USING      (EXISTS (
    SELECT 1 FROM app_pages p_app_pages
     WHERE p_app_pages.id = app_transitions.from_page_id
       AND EXISTS (
       SELECT 1 FROM applications p2_applications
        WHERE p2_applications.id = p_app_pages.application_id
          AND EXISTS (
       SELECT 1 FROM projects p2_projects
        WHERE p2_projects.id = p2_applications.project_id
          AND p2_projects.org_id = current_setting('app.current_org_id', true)::uuid))))
  WITH CHECK (EXISTS (
    SELECT 1 FROM app_pages p_app_pages
     WHERE p_app_pages.id = app_transitions.from_page_id
       AND EXISTS (
       SELECT 1 FROM applications p2_applications
        WHERE p2_applications.id = p_app_pages.application_id
          AND EXISTS (
       SELECT 1 FROM projects p2_projects
        WHERE p2_projects.id = p2_applications.project_id
          AND p2_projects.org_id = current_setting('app.current_org_id', true)::uuid))));
