#!/usr/bin/env tsx
/**
 * `qa db:gen-rls`
 *
 * Emits database/sql/011_rls_enable.sql and database/sql/012_rls_policies.sql
 * from the two maps below. Generated, not hand-maintained — see
 * 08-TEAM-SYSTEMS.md §3.3: "a hand-maintained list is the thing §3.6 [the CI
 * coverage audit] exists to catch."
 *
 * DIRECT_TABLES carry `org_id` themselves. CHILD_TABLES are reached through
 * exactly one parent hop each; the generator walks the chain until it hits a
 * direct table and composes one EXISTS per hop, innermost first, matching the
 * hand-written examples in 08-TEAM-SYSTEMS.md §3.4 (test_steps, applications,
 * execution_steps).
 *
 * Keep this map in sync with database/schema.prisma. The CI job
 * `rls-coverage` (see 08-TEAM-SYSTEMS.md §3.6) fails the build if a
 * tenant-reachable table exists in the schema but not here.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";

const DIRECT_TABLES = [
  "org_entitlements", "usage_records", "identity_providers", "domain_claims",
  "invitations", "support_access_grants", "users", "memberships", "audit_logs",
  "projects", "embeddings", "tests", "agents", "tenant_agent_pins",
  "agent_runs", "executions", "artifacts", "failures", "issues",
];

/** table -> [parentTable, fkColumnOnThisTable] */
const CHILD_TABLES: Record<string, [string, string]> = {
  project_members: ["projects", "project_id"],
  refresh_tokens: ["users", "user_id"],
  key_counters: ["projects", "project_id"],
  folders: ["projects", "project_id"],
  tags: ["projects", "project_id"],
  test_plans: ["projects", "project_id"],
  quality_snapshots: ["projects", "project_id"],
  applications: ["projects", "project_id"],
  test_steps: ["tests", "test_id"],
  test_preconditions: ["tests", "test_id"],
  test_validations: ["tests", "test_id"],
  test_versions: ["tests", "test_id"],
  test_tags: ["tests", "test_id"],
  test_data_sets: ["tests", "test_id"],
  test_dependencies: ["tests", "test_id"],
  agent_tool_grants: ["agents", "agent_id"],
  agent_actions: ["agent_runs", "agent_run_id"],
  ai_proposals: ["agent_runs", "agent_run_id"],
  healing_attempts: ["agent_runs", "agent_run_id"],
  failure_analyses: ["agent_runs", "agent_run_id"],
  execution_tests: ["executions", "execution_id"],
  execution_events: ["executions", "execution_id"],
  issue_tests: ["issues", "issue_id"],
  issue_comments: ["issues", "issue_id"],
  issue_history: ["issues", "issue_id"],
  issue_artifacts: ["issues", "issue_id"],
  environments: ["applications", "application_id"],
  app_pages: ["applications", "application_id"],
  app_flows: ["applications", "application_id"],
  explorations: ["applications", "application_id"],
  execution_steps: ["execution_tests", "execution_test_id"],
  app_credentials: ["environments", "environment_id"],
  app_components: ["app_pages", "page_id"],
  app_elements: ["app_pages", "page_id"],
  app_flow_pages: ["app_flows", "flow_id"],
  app_transitions: ["app_pages", "from_page_id"],
};

const ALL_TABLES = [...DIRECT_TABLES, ...Object.keys(CHILD_TABLES)];

function assertAcyclic() {
  for (const table of Object.keys(CHILD_TABLES)) {
    const seen = new Set<string>([table]);
    let cur = table;
    let hops = 0;
    while (CHILD_TABLES[cur]) {
      const [parent] = CHILD_TABLES[cur];
      if (seen.has(parent)) throw new Error(`CHILD_TABLES cycle detected at "${table}"`);
      seen.add(parent);
      cur = parent;
      if (++hops > 10) throw new Error(`CHILD_TABLES chain too deep at "${table}" (check for a typo)`);
    }
    if (!DIRECT_TABLES.includes(cur)) {
      throw new Error(`"${table}" does not resolve to a DIRECT_TABLES entry (stuck at "${cur}")`);
    }
  }
}

function genEnableSql(): string {
  const lines = ALL_TABLES.map((t) => `    '${t}'`).join(",\n");
  return `-- 011_rls_enable.sql
-- GENERATED by \`pnpm db:gen-rls\` (database/scripts/gen-rls.ts). Do not hand-edit.
-- One ENABLE + FORCE per tenant-reachable table. See 08-TEAM-SYSTEMS.md §3.3.

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
${lines}
  ]
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE public.%I FORCE  ROW LEVEL SECURITY', t);
  END LOOP;
END $$;
`;
}

/**
 * Builds the nested EXISTS predicate for a child table, innermost hop first.
 * The outermost hop qualifies the FK column with the policy table's own name
 * — inside a RLS policy body, unqualified/table-qualified column references
 * resolve to the row currently being checked. There is no FROM clause for
 * the policy table itself, so it must never be given a bare alias.
 */
function buildExistsPredicate(table: string): string {
  const [parentTable, fkColumn] = CHILD_TABLES[table];
  const parentAlias = `p_${parentTable}`;

  if (DIRECT_TABLES.includes(parentTable)) {
    return `EXISTS (
    SELECT 1 FROM ${parentTable} ${parentAlias}
     WHERE ${parentAlias}.id = ${table}.${fkColumn}
       AND ${parentAlias}.org_id = current_setting('app.current_org_id', true)::uuid)`;
  }

  const inner = buildExistsPredicateFor(parentTable, parentAlias);
  return `EXISTS (
    SELECT 1 FROM ${parentTable} ${parentAlias}
     WHERE ${parentAlias}.id = ${table}.${fkColumn}
       AND ${inner})`;
}

// Same as buildExistsPredicate but parameterized on the alias of the row
// being checked (used recursively for multi-hop chains).
function buildExistsPredicateFor(table: string, alias: string): string {
  const [parentTable, fkColumn] = CHILD_TABLES[table];
  const parentAlias = `p2_${parentTable}`;
  if (DIRECT_TABLES.includes(parentTable)) {
    return `EXISTS (
       SELECT 1 FROM ${parentTable} ${parentAlias}
        WHERE ${parentAlias}.id = ${alias}.${fkColumn}
          AND ${parentAlias}.org_id = current_setting('app.current_org_id', true)::uuid)`;
  }
  const inner = buildExistsPredicateFor(parentTable, parentAlias);
  return `EXISTS (
       SELECT 1 FROM ${parentTable} ${parentAlias}
        WHERE ${parentAlias}.id = ${alias}.${fkColumn}
          AND ${inner})`;
}

function genPoliciesSql(): string {
  const direct = DIRECT_TABLES.map(
    (t) => `CREATE POLICY tenant_isolation ON ${t}
  USING      (org_id = current_setting('app.current_org_id', true)::uuid)
  WITH CHECK (org_id = current_setting('app.current_org_id', true)::uuid);`,
  ).join("\n\n");

  const children = Object.keys(CHILD_TABLES).map((t) => {
    const predicate = buildExistsPredicate(t);
    return `CREATE POLICY tenant_isolation ON ${t}
  USING      (${predicate})
  WITH CHECK (${predicate});`;
  }).join("\n\n");

  return `-- 012_rls_policies.sql
-- GENERATED by \`pnpm db:gen-rls\` (database/scripts/gen-rls.ts). Do not hand-edit.
-- See 08-TEAM-SYSTEMS.md §3.3-3.4 for the USING/WITH CHECK rationale and the
-- EXISTS-subquery-over-denormalization decision for child tables.

-- ── Direct: org_id is a column on the table itself ──────────────────────────

${direct}

-- ── Reached via a parent (one predicate per hop, innermost first) ───────────

${children}
`;
}

function main() {
  assertAcyclic();
  const sqlDir = join(__dirname, "..", "sql");
  writeFileSync(join(sqlDir, "011_rls_enable.sql"), genEnableSql());
  writeFileSync(join(sqlDir, "012_rls_policies.sql"), genPoliciesSql());
  console.log(
    `[gen-rls] wrote 011_rls_enable.sql and 012_rls_policies.sql — ` +
      `${DIRECT_TABLES.length} direct + ${Object.keys(CHILD_TABLES).length} child tables ` +
      `= ${ALL_TABLES.length} policies.`,
  );
}

main();
